update script

diff --git a/common b/common
--- a/common
+++ b/common
@@ -119,3 +119,54 @@ updateImages() {
     fi
 
 }
+
+copyDataBaseDump() {
+    #Download dump and run mysql container
+    echo "Show available dump"
+    ssh "$SSH_USERNAME"@"$REMOTE_HOST" sudo ls -l "$ASSETS_FOLDER/$1/$2"
+
+    if [ ! $? -eq 0 ]; then
+        echo "Failed attempt ssh connection for $SSH_USERNAME to $REMOTE_HOST"
+        exit
+    fi
+    read -p "Choice sql file to init database: " sqlDump
+
+    checkFileExist=true
+    while $checkFileExist; do
+        ssh "$SSH_USERNAME"@"$REMOTE_HOST" sudo cp "$ASSETS_FOLDER/$1/$2/$sqlDump /home/$SSH_USERNAME"
+
+        if [ $? -eq 0 ]
+        then
+            if [ -e ./init-db ]
+            then
+                rm -rf ./init-db/*
+            else
+                mkdir ./init-db
+            fi
+            scp -r "$SSH_USERNAME"@"$REMOTE_HOST":"/home/$SSH_USERNAME/$sqlDump" ./init-db
+            checkFileExist=false
+        else
+            read -p "Choice a valid sql file: " sqlDump
+        fi
+    done
+}
+
+# Copy renamed specific settings file
+copySettings() {
+    if [ $AVAILABLE_PLATFORM == drupal ]
+    then
+        if [ -e "$DOCUMENT_ROOT"sites/example.settings.docker.local-env."$branchNameDashed".php ]; then
+            if [ -e "$PROJECT_ASSETS_FOLDER"settings.php ];then
+                chmod 777 "$PROJECT_ASSETS_FOLDER"settings.php
+            fi
+            cp "$DOCUMENT_ROOT"sites/example.settings.docker.local-env."$branchNameDashed".php "$PROJECT_ASSETS_FOLDER"settings.php
+        fi
+
+        if [ -e "$DOCUMENT_ROOT"sites/example.settings.local.localdev.php ]; then
+            if [ -e "$PROJECT_ASSETS_FOLDER"settings.local.php ];then
+                chmod 777 "$PROJECT_ASSETS_FOLDER"settings.php
+            fi
+            cp "$DOCUMENT_ROOT"sites/example.settings.local.localdev.php "$PROJECT_ASSETS_FOLDER"settings.local.php
+        fi
+    fi
+}
