update startPhpApache for wordpress projects

diff --git a/startPhpApache b/startPhpApache
--- a/startPhpApache
+++ b/startPhpApache
@@ -1,50 +1,55 @@
 #!/usr/bin/env bash
 
 . `pwd`/docker-config/config.sh
+. common
 
-#Update assets
+# Update assets
 updateImages() {
 
-    #Update Assets
-    echo "Show active projects"
-    ls -l "$ASSETS_FOLDER"
     echo -n "Which project do you want to synchronize? "
     read projectInput
 
     #Copy drupal assets and settings
     if [[ "$AVAILABLE_PLATFORM" == wordpress ]]
     then
-        echo "Start copy FROM $ASSETS_FOLDER/$projectInput/$branchInput/uploads TO $PROJECT_ASSETS_FOLDER"
+        echo "$SSH_USERNAME"@"$REMOTE_HOST":"/home/$SSH_USERNAME/uploads.zip TO $PROJECT_ASSETS_FOLDER"
         sleep 5
-        cp -R "$ASSETS_FOLDER/$projectInput/$branchInput/uploads" "$PROJECT_ASSETS_FOLDER"
+        ssh "$SSH_USERNAME"@"$REMOTE_HOST" sudo cp "$ASSETS_FOLDER/$projectInput/$branchInput/uploads.zip /home/$SSH_USERNAME"
+        if [ $? -eq 0 ]; then
+            scp -r "$SSH_USERNAME"@"$REMOTE_HOST":"/home/$SSH_USERNAME/uploads.zip" "$PROJECT_ASSETS_FOLDER"
+            if [ $? -eq 0 ]; then
+                echo "uploads.zip has been copied inside $PROJECT_ASSETS_FOLDER"
+                cd "$PROJECT_ASSETS_FOLDER"
+                unzip uploads.zip
+                if [ $? -eq 0 ]; then
+                    echo "Uploads folder has been unzipped"
+                    rm -rf "$PROJECT_ASSETS_FOLDER/uploads.zip"
+                else
+                    echo "Failed attempt to unzip uploads folder. Do you have unzip command installed? Check and retry"
+                    exit
+                fi
+
+            else
+                echo "Failed attempt ssh connection for $SSH_USERNAME to $REMOTE_HOST"
+                exit
+            fi
+        else
+            echo "Failed attempt ssh connection for $SSH_USERNAME to $REMOTE_HOST"
+            exit
+        fi
     fi
 
     #ToDo: other platforms
 }
 
-echo -n "Which project do you want to synchronize? Type a name: "
-read projectInput
-
-echo "Show active branches"
-git branch --all
-echo "--------------------"
-
-#Update source code
-echo -n "Which branch do you want to use? The system will take care to checkout and pull automatically: "
-read branchInput
-if [[ -n "$branchInput" ]]
-then
-    git checkout "$branchInput" && git pull origin "$branchInput"
-else
-    echo "ERROR: No branch selected"
-    exit
-fi
+checkDockerStatus
+choiceBranch
 
 read -p "Do you want to synchronize assets folder [Yy/Nn]?" yn
 checkDockerStatus=true
 while $checkDockerStatus; do
     case $yn in
-        [Yy] ) updateImages
+        [Yy] ) showActiveProjects
                checkDockerStatus=false
                ;;
         [Nn] ) echo "Assets not will be synchronized"
